# Generated by Django 4.2.2 on 2023-06-26 02:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TblMovilidad',
            fields=[
                ('movilidad_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_tipo_servicio', models.CharField(max_length=45)),
                ('movilidad_turno', models.CharField(max_length=45)),
                ('movilidad_seccion', models.CharField(max_length=45)),
                ('movilidad_docente', models.CharField(max_length=255)),
                ('movilidad_pago', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='TblMovilidadRuta',
            fields=[
                ('movilidad_ruta_id', models.AutoField(primary_key=True, serialize=False)),
                ('movilidad_ruta_direccion', models.CharField(max_length=255)),
                ('movilidad_ruta_hora_recojo', models.TimeField(blank=True, null=True)),
                ('movilidad_ruta_hora_retorno', models.TimeField(blank=True, null=True)),
                ('movilidad', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='rutas.tblmovilidad')),
            ],
        ),
    ]
